### ISSUE TITLE
Prototype data profiling API

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/mit-matching#3]
API accepts:
* dataset in CSV format
* [Optional] associated publication text
* [Optional] description of dataset
* [Optional] data dictionary of arbitrary form

API returns:
* Proposed mapping of columns to DKG concepts [nullable]
* Inferred units per column [nullable]
* other relevant extraction/classification

For an MVP let's start with some data that was used for the evaluation. I'll post that as a follow-up comment once I've got it organized.

**Comment by brandomr** [comment]
[This data](https://github.com/DARPA-ASKEM/experiments/tree/main/thin-thread-examples/milestone_6month/evaluation/ta1) from the 6 month evaluation would be good to use as a starting point @Tranway1

**Comment by Tranway1** [comment]
Please see the csv dataset connection to dkg example.
https://github.com/DARPA-ASKEM/mit-matching/commit/b300fb34d827fb226f3095a51baec3d7b181172b
